### ISSUE TITLE
[query] Where should hyprsysteminfo fetch the text color. 

### ISSUE THREAD

**Issue by kRHYME7** [hyprwm/hyprsysteminfo#11]
It kinda gets the theme and it kinda not. 
![image](https://github.com/user-attachments/assets/c2aa88d3-b1cf-4005-b784-50a4a33f47ab)
![image](https://github.com/user-attachments/assets/7001201c-9d7e-4393-91aa-910133f18834)

# I'm referencing with Kvantum BTW.
![image](https://github.com/user-attachments/assets/1af81d63-a027-44ae-b987-3c0944f5ba9e)
![image](https://github.com/user-attachments/assets/484201ea-ccf5-47af-8cf5-45aea8a2a591)

I have  qt*ct and kvantum for QT theming

**Comment by vaxerski** [comment]
blame @outfoxxed. SHould be fixed once he will do hyprqml. For now I can quickly patch it.

**Comment by kRHYME7** [comment]
Works as expected. Thanks!
