### ISSUE TITLE
Text doesn't respond to the window size

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprsysteminfo#2]
![immagine](https://github.com/user-attachments/assets/26932034-fcd2-4a94-8e63-2616233a76df)

I guess this isn't really an issue as the window can't be resized but I can't see the end of the commit hash as it's clipped (I can in fullscreen) and the ... after cpu and gpu name stay regardless of whether they could fit.

**Comment by vaxerski** [comment]
what scale is this? damn

**Comment by alba4k** [comment]
1 on a 1920x1200

sorry wanted to type that but forgot

**Comment by Soccera1** [comment]
That's weird. Using my laptop (1920x1200) at 100% scaling, this isn't an issue.

**Comment by Soccera1** [comment]
![2024-10-14-055747_hyprshot](https://github.com/user-attachments/assets/bc9ebe4e-25e6-466c-bf46-aa0a87702762)
Here is a screenshot

**Comment by alba4k** [comment]
You're also using a tagged release so the commit name is simply not shown

**Comment by Soccera1** [comment]
I was more referring to the CPU name.

**Comment by alba4k** [comment]
That is because yours is shorter

It also happens on vaxry's machine as you can see from the README

**Comment by Soccera1** [comment]
The only difference between our CPUs is that you have a 60P and I have a 55U, along with you having a 6 instead of a 2. That's unless I've counted catastrophically wrong.

**Comment by vaxerski** [comment]
made the thing a bit bigger. Better?

**Comment by alba4k** [comment]
![immagine](https://github.com/user-attachments/assets/7d2ca08a-d03f-41eb-90d8-c3bf185340d5)

Works fine now

Would still nice to be able to see the full cpu/gpu name once the window is made bigger / fullscreened instead of it always showing ... but I guess that's not a real issue as you're not supposed to be able to resize it

**Comment by Kn0ax** [comment]
![image](https://github.com/user-attachments/assets/ea26b9ec-9f0a-4c05-b319-28798861178d)
another truncation case

**Comment by alba4k** [comment]
That is what I was already referring to tho?
